default:
  type: postgres
  host: http://34.82.17.186
  port: 3306
  username: ahmet
  password: ahmet123
  database: emece
  synchronize: true
  logging: true
  entities:
    - src/**/*.entity.ts
    - dist/**/*.entity.js
  migrations:
    - database/migrations/**/*.ts
    - dist/database/migrations/**/*.js
  subscribers:
    - database/subscriber/**/*.ts
    - dist/database/subscriber/**/.js
  cli:
    entitiesDir: src
    migrationsDir: database/migrations
    subscribersDir: database/subscriber
